# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 9021
  servlet:
    # 应用的访问路径
    context-path: /sys
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200


# 数据源配置
spring:
  application:
    name: /sys-service
  thymeleaf:
    cache: false
    servlet:
      content-type: text/html
    mode: HTML
    prefix: classpath:/swagger.1.0-version/
    suffix: .html
    enabled: true
    encoding: UTF-8
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/lanx-enterprise-data-center?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username:
        login-password:
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true

    # 数据源配置
  servlet:
    multipart:
      # 开启 multipart 上传功能
      enabled: true
      # 文件写入磁盘的阈值
      file-size-threshold: 2KB
      # 最大文件大小
      max-file-size: 200MB
      # 最大请求大小
      max-request-size: 215MB

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:mybatis/*Mapper.xml
  #  config-location: classpath:mybatis/mybatis-config.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#swagger配置
swagger:
  docs:
    config:
      project-path: D:\Project\Love\love-sys
      project-name: 用户管理配置
      api-version: 1.0-version
      docs-path: D:\Project\Love\love-sys\src\main\resources\swagger
      auto-generate: true

